# Generated by Django 2.1.7 on 2019-10-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Test',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='price',
            new_name='result',
        ),
    ]
